use std::fmt::Write;
use std::path::Path;

use deepwoken_rs::Stat;
use deepwoken_rs::model::stat;

fn format_array(stats: &[Stat]) -> String {
    let items: Vec<String> = stats.iter().map(|s| format!("\"{}\"", s.name())).collect();
    format!("[{}]", items.join(", "))
}

fn main() {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by build.rs do not edit thanks").unwrap();
    writeln!(out).unwrap();

    // thge stat type union
    let all_stats: Vec<Stat> = (0u32..).map_while(|i| Stat::try_from(i).ok()).collect();

    let literals: Vec<String> = all_stats
        .iter()
        .map(|s| format!("\"{}\"", s.name()))
        .collect();

    writeln!(out, "export type Stat = {};", literals.join(" | ")).unwrap();
    writeln!(out).unwrap();

    // constant arrays
    writeln!(
        out,
        "export const CORE_STATS: Stat[] = {};",
        format_array(stat::CORE)
    )
    .unwrap();
    writeln!(
        out,
        "export const WEAPON_STATS: Stat[] = {};",
        format_array(stat::WEAPON)
    )
    .unwrap();
    writeln!(
        out,
        "export const ATTUNEMENT_STATS: Stat[] = {};",
        format_array(stat::ATTUNEMENT)
    )
    .unwrap();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest = Path::new(&manifest_dir).join("generated.ts");
    std::fs::write(&dest, out).unwrap();

    println!("cargo::rerun-if-changed=../rust/src/model/stat.rs");
}
