use std::fmt::Write;
use std::path::Path;

use deepwoken_rs::Stat;
use deepwoken_rs::model::stat;
use deepwoken_rs::model::enums::{
    EquipmentSlot, ItemRarity, MantraType, RangeType, TalentRarity, WeaponType,
};

fn format_array(stats: &[Stat]) -> String {
    let items: Vec<String> = stats.iter().map(|s| format!("\"{}\"", s.name())).collect();
    format!("[{}]", items.join(", "))
}

fn write_union<T: Copy>(out: &mut String, name: &str, variants: &[T], namer: fn(&T) -> &str) {
    let literals: Vec<String> = variants.iter().map(|v| format!("\"{}\"", namer(v))).collect();
    writeln!(out, "export type {name} = {};", literals.join(" | ")).unwrap();
}

fn write_const_array<T: Copy>(out: &mut String, name: &str, ts_type: &str, variants: &[T], namer: fn(&T) -> &str) {
    let items: Vec<String> = variants.iter().map(|v| format!("\"{}\"", namer(v))).collect();
    writeln!(out, "export const {name}: {ts_type}[] = [{}];", items.join(", ")).unwrap();
}

fn main() {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by build.rs do not edit thanks").unwrap();
    writeln!(out).unwrap();

    // Stat
    let all_stats: Vec<Stat> = (0u32..).map_while(|i| Stat::try_from(i).ok()).collect();
    let literals: Vec<String> = all_stats.iter().map(|s| format!("\"{}\"", s.name())).collect();
    writeln!(out, "export type Stat = {};", literals.join(" | ")).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "export const CORE_STATS: Stat[] = {};", format_array(stat::CORE)).unwrap();
    writeln!(out, "export const WEAPON_STATS: Stat[] = {};", format_array(stat::WEAPON)).unwrap();
    writeln!(out, "export const ATTUNEMENT_STATS: Stat[] = {};", format_array(stat::ATTUNEMENT)).unwrap();
    writeln!(out).unwrap();

    // ItemRarity
    write_union(&mut out, "ItemRarity", ItemRarity::ALL, ItemRarity::name);
    write_const_array(&mut out, "ITEM_RARITIES", "ItemRarity", ItemRarity::ALL, ItemRarity::name);
    writeln!(out).unwrap();

    // TalentRarity
    write_union(&mut out, "TalentRarity", TalentRarity::ALL, TalentRarity::name);
    write_const_array(&mut out, "TALENT_RARITIES", "TalentRarity", TalentRarity::ALL, TalentRarity::name);
    writeln!(out).unwrap();

    // WeaponType
    write_union(&mut out, "WeaponType", WeaponType::ALL, WeaponType::name);
    write_const_array(&mut out, "WEAPON_TYPES", "WeaponType", WeaponType::ALL, WeaponType::name);
    writeln!(out).unwrap();

    // EquipmentSlot
    write_union(&mut out, "EquipmentSlot", EquipmentSlot::ALL, EquipmentSlot::name);
    write_const_array(&mut out, "EQUIPMENT_SLOTS", "EquipmentSlot", EquipmentSlot::ALL, EquipmentSlot::name);
    writeln!(out).unwrap();

    // RangeType
    write_union(&mut out, "RangeType", RangeType::ALL, RangeType::name);
    writeln!(out).unwrap();

    // MantraType
    write_union(&mut out, "MantraType", MantraType::ALL, MantraType::name);
    writeln!(out).unwrap();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let dest = Path::new(&manifest_dir).join("generated.ts");
    std::fs::write(&dest, out).unwrap();

    println!("cargo::rerun-if-changed=../rust/src/model/stat.rs");
    println!("cargo::rerun-if-changed=../rust/src/model/enums.rs");
}
