// AUTO-GENERATED by build.rs do not edit thanks

export type Stat = "Strength" | "Fortitude" | "Agility" | "Intelligence" | "Willpower" | "Charisma" | "Heavy" | "Medium" | "Light" | "Frostdraw" | "Flamecharm" | "Thundercall" | "Galebreathe" | "Shadowcast" | "Ironsing" | "Bloodrend";

export const CORE_STATS: Stat[] = ["Strength", "Fortitude", "Agility", "Intelligence", "Willpower", "Charisma"];
export const WEAPON_STATS: Stat[] = ["Heavy", "Medium", "Light"];
export const ATTUNEMENT_STATS: Stat[] = ["Flamecharm", "Frostdraw", "Thundercall", "Galebreathe", "Shadowcast", "Ironsing", "Bloodrend"];
